# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ivdfl3wTU_74ZOi5KNYBMbW6ty0ymibh
"""

def add(n1,n2):
  print(n1+n2)
def substract(n1,n2):
  print(n1-n2)
def multiply(n1,n2):
  print(n1*n2)
def exponent(n1,n2):
  print(n1**n2)
def divide(n1,n2):
  print(n1/n2)
n1 = int(input("Enter number n1 : "))
n2 = int(input("Enter a number n2 : "))
while True :
  print("Menu \n A. Add\n B. Substract\n C. Multiply\n D.Divide \n E. Exponent")
  option = input("Select an option above: ").lower()
  if option == "a":
    add(n1,n2)
  elif option == "b":
    substract(n1,n2)
  elif option == "c":
    multiply(n1,n2)
  elif option == "d":
    divide(n1,n2)
  elif option == "e":
    exponent(n1,n2)
  repeat = input("Do you want to continue : ").lower()
  if repeat == "no":
    break